### ISSUE TITLE
Pathifier fails in Princurve

### ISSUE THREAD

**Issue by sriganeshms** [dynverse/princurve#27]
Hi, I have been using Pathifier since quite some time. However, recently, it is failing with the following error, possibly due to an update to the princurve package:

Error in project_to_curve(x, s = start, stretch = stretch) : 
  Expecting a single value:

**Comment by rcannood** [comment]
Hello Sriganesh,

This was actually a problem in Pathifier, which only came to light because the new princurve checks its parameters a bit better. However, this should have been fixed with Pathifier 1.20.0. Could you try updating Pathifier?

Kind regards,
Robrecht

**Comment by sriganeshms** [comment]
Thanks, Robrecht! I will try updating Pathifier.


-- Sriganesh

On Thu, Aug 16, 2018 at 5:17 PM, Robrecht Cannoodt <notifications@github.com

**Comment by rcannood** [comment]
Has this solved your issue? :)

**Comment by sriganeshms** [comment]
Hi Robrecht, yes it did. Thanks :)

-- Sriganesh

**Comment by rcannood** [comment]
Great to hear!
