### ISSUE TITLE
SystemRequirements: ImageMagick++?

### ISSUE THREAD

**Issue by HenrikBengtsson** [dynverse/princurve#28]
Is the following really required:
```
SystemRequirements: ImageMagick++: ImageMagick-c++-devel (rpm) or libmagick++-dev (deb)
```
or is it related to {magick} being Suggests:ed?

Background: Having experienced enough out-dated academic compute environments in my life, I find it unfortunate if {princurve} gains *required* dependencies that are not relevant to the core business and that may complicate and even prevent installation for end users.  For instance, it can take days, weeks, months, to convince sysadms to install a missing system library.

**Comment by rcannood** [comment]
Hello Henrik, 

It is indeed only Suggested. Would you recommend the system requirements to be displayed differently? I could also just remove the vignettes altogether.

Robrecht

**Comment by gavinsimpson** [comment]
Then I don't think **princurve** should have this stated. Writing R Extensions (WRE) says

> Dependencies external to the R system should be listed in the ‘SystemRequirements’ field...

As such the libraries currently listed in `System Requirements` are not dependencies of **princurve** but of the **magick** package, which presumably has the appropriate `SystemRequirements`?

You shouldn't need to do anything other than list **magick** in `Suggests` to use it in the Vignette. (You may want to check what WRE says about using `Suggests` packages *conditionally* in examples, tests, and vignettes.)

**Comment by rcannood** [comment]
@HenrikBengtsson I removed any exotic packages from the DESCRIPTION to ensure backward compatibility. Is the current state of the @devel branch ok for you?

**Comment by HenrikBengtsson** [comment]
I think only need to remove the `SystemRequirements`.  It's ok to keep `Suggests`:ed package.
I also think it is ok to use those in the vignette.

Note that vignettes are pre-built during `R CMD build` (`vignettes/` is processed and `docs/` is produced).   Vignettes are _not_ built during `R CMD install`, which means it is ok to keep dependencies on the {magick} package etc in there.  A user without {magick}, will still be able to install {princurve}, i.e. `Suggests:` dependencies are _not_ a show stopper.

**Comment by rcannood** [comment]
I was unsatisfied with the vignette, which is why I decided to remove it for now. I'll create a new one when I have the time for it. I'll be merging the devel branch now :)
