### ISSUE TITLE
CLARIFICATION: An R port OR the Trevor Hastie's Principal Curve package?

### ISSUE THREAD

**Issue by HenrikBengtsson** [dynverse/princurve#7]
The https://cran.r-project.org/package=princurve points to this GitHub repos (https://github.com/dynverse/princurve/).  OTH, the GitHub page title reads:

"An R port of Trevor Hastie's Principal Curve package"

and, similarly, the README reads:

"This is an R port of Trevor Hastie's Principal Curve package."

Given that this is the official repository of the princurve package - it's confusing when it mentions "an R port".  Could you please clarify this and then change behind this here on GitHub?

**Comment by rcannood** [comment]
The reason for this description was that Trevor Hastie originally implemented principal curves in S. `princurve` always has been an R port of Trevor Hastie's package, but perhaps this is less relevant than it used to be.

Thanks for the suggestion, I've changed the readme and the github page title to match with the description in the R package (27a5169baf00b42e9309ca1e0408603a3f51fa31).

**Comment by HenrikBengtsson** [comment]
Ah... I forgot about that history - Trevor Hastie wrote the original version in S and Andreas Weingessel ported it to R.  Thanks for a clarifying this.
